version: 2.1

orbs:
  node: circleci/node@5.0.2
  cypress: cypress-io/cypress@1
  jest: blimmer/jest@1.1.0

workflows:
  build:
    jobs:
      - cypress/run:
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
      - jest/test

  deploy_preview:
    name: deploy
    filters:
      branches:
        ignore:
          - main
    requires:
      - cypress/run
      - jest/test
    jobs:
      - npm install --global vercel
      - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - vercel build --token=$VERCEL_TOKEN
      - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

  deploy_production:
    name: deploy
    filters:
      branches:
        only:
          - main
    requires:
      - cypress/run
      - jest/test
    jobs:
      - npm install --global vercel
      - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - vercel build --prod --token=$VERCEL_TOKEN
      - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
