version: 2.1

orbs:
  node: circleci/node@5.0.2
  cypress: cypress-io/cypress@1
  jest: blimmer/jest@1.1.0

workflows:
  version: 2
  stack:
    jobs:
      - jest/test
      - cypress/run:
          requires:
            - jest/test
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
      - deploy:
          requires:
            - cypress/run

jobs:
  deploy:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout
      - run:
          name: Check Node version
          command: node --version
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Deploy to Vercel
          command: |
            if [ $CIRCLE_BRANCH == "main" ]; then
            sudo npm install --global vercel
            vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            vercel build --prod --token=$VERCEL_TOKEN
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

            else
            sudo npm install --global vercel
            vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
            vercel build --token=$VERCEL_TOKEN
            vercel deploy --prebuilt  --token=$VERCEL_TOKEN

            fi
