name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
