name: CI/CD Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
jobs:
  call-tests-workflow:
    uses: ./.github/workflows/tests.yaml
  # Unit-Tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run Jest
  #       run: npm run test:unit

  # E2E-Tests:
  #   runs-on: ubuntu-latest
  #   needs: Unit-Tests
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run Cypress
  #       uses: cypress-io/github-action@v4
  #       with:
  #         command: npm run test:e2e

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: E2E-Tests
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
